spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_BROKERS}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_SASL_USERNAME}" password="${KAFKA_SASL_PASSWORD}";

crawler:
  topicReplicas: 2

logging:
  level:
    root: WARN
    nz.govt.eop: INFO
