spring:
  application:
    name: hilltop-crawler
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        max.request.size: 134217728
        buffer.memory: 134217728
      compression-type: gzip

    streams:
      properties:
        num.stream.threads: 8
        producer.max.request.size: 10485760
        producer.compression.type: gzip
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      application-id: nz.govt.eop.consumers.hilltop-crawler

  datasource:
    url: jdbc:postgresql://${CONFIG_DATABASE_HOST:localhost}:${CONFIG_DATABASE_PORT:5432}/${CONFIG_DATABASE_NAME:eop_dev}
    username: ${CONFIG_DATABASE_USERNAME:postgres}
    password: ${CONFIG_DATABASE_PASSWORD:password}
    hikari:
      schema: hilltop_crawler

  flyway:
    schemas: hilltop_crawler
    locations: classpath:/db/migration
    user: ${CONFIG_DATABASE_MIGRATIONS_USERNAME:eop_hilltop_crawler_migrations_user}
    password: ${CONFIG_DATABASE_MIGRATIONS_PASSWORD:password}

  task:
    scheduling:
      pool:
        size: 10

crawler:
  topicReplicas: 1

logging:
  level:
    root: INFO
    nz.govt.eop: DEBUG
