version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/packages/HilltopCrawler"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "gradle"
      - "dependencies"      
      
  - package-ecosystem: "gradle"
    directory: "/packages/IngestAPI"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "gradle"
      - "dependencies"      

  - package-ecosystem: "gradle"
    directory: "/packages/Manager"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "gradle"
      - "dependencies"      

  - package-ecosystem: "npm"
    directory: "/packages/PlanLimitsUI"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"      

  - package-ecosystem: "npm"
    directory: "/packages/RainfallViewer"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2    
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/docs-site"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/packages/cccv"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "npm"
      - "dependencies"
