version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/packages/HilltopCrawler"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "gradle"
      - "dependencies"
      - "hilltop crawler"
    groups:
       flyway-deps:
          patterns:
            - "org.flyway*"     
      
  - package-ecosystem: "gradle"
    directory: "/packages/IngestAPI"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "gradle"
      - "dependencies"
      - "ingest api"      

  - package-ecosystem: "gradle"
    directory: "/packages/Manager"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "gradle"
      - "dependencies"
      - "manager"
    groups:
       flyway-deps:
          patterns:
            - "org.flyway*"       

  - package-ecosystem: "npm"
    directory: "/packages/PlanLimitsUI"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "plan limits ui"

  - package-ecosystem: "npm"
    directory: "/docs-site"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "docs site"

  - package-ecosystem: "npm"
    directory: "/packages/cccv"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "npm"
      - "dependencies"
      - "cccv"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/packages/DataTransformation"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "docker"
      - "dependencies"
      - "data transformation"