export const siteNames: Array<{ id: number; siteName: string; aliases: string[]; explanation: string }> = [
    {id: 1, siteName: "Ara hikoi", aliases: [], explanation: "Walking path"},
    {id: 2, siteName: "Ara waka", aliases: [], explanation: "Traditional canoe route"},
    {id: 3, siteName: "Hoe waka", aliases: [], explanation: "Canoe place"},
    {id: 4, siteName: "Kai awa", aliases: [], explanation: "Freshwater foods"},
    {id: 5, siteName: "Kai Māori", aliases: [], explanation: "Māori foods"},
    {id: 6, siteName: "Kai moana", aliases: [], explanation: "Food harvested from the sea"},
    {id: 7, siteName: "Kai ngahere", aliases: [], explanation: "Forest foods"},
    {id: 8, siteName: "Kāinga", aliases: [], explanation: "Home"},
    {id: 9, siteName: "Kānga wai", aliases: [], explanation: "Fermented corn"},
    {id: 10, siteName: "Kauhoe", aliases: [], explanation: "Swimming"},
    {id: 11, siteName: "Kaukau", aliases: [], explanation: "Bathing"},
    {id: 12, siteName: "Kohatu hoanga", aliases: [], explanation: "Sandstone"},
    {id: 13, siteName: "Kohatu kiripaka", aliases: [], explanation: "Flint, quartz"},
    {id: 14, siteName: "Koiwi", aliases: [], explanation: "Human skeletal remains"},
    {id: 15, siteName: "Kōrero pūrākau", aliases: [], explanation: "Ancient legend"},
    {id: 16, siteName: "Koura", aliases: [], explanation: "Fresh and saltwater crayfish"},
    {id: 17, siteName: "Mahi pārekareka", aliases: [], explanation: "Enjoyment"},
    {id: 18, siteName: "Mahi tauhokohoko", aliases: [], explanation: "Trade"},
    {id: 19, siteName: "Mahi whakairo", aliases: [], explanation: "Carving"},
    {
        id: 20,
        siteName: "Mahinga kai",
        aliases: [],
        explanation: "The customary gathering of food and natural materials, the food and resources themselves and the places where those resources are gathered."
    },
    {id: 21, siteName: "Mahinga mataitai", aliases: [], explanation: "Customary seafood gathering site"},
    {id: 22, siteName: "Mahinga tuna", aliases: [], explanation: "Eel harvesting place"},
    {id: 23, siteName: "Mara kai", aliases: [], explanation: "Garden"},
    {id: 24, siteName: "Marae", aliases: [], explanation: "Courtyard, open area in front of wharenui"},
    {
        id: 25,
        siteName: "Ngā mahi pākarekareka i/ki te wai",
        aliases: [],
        explanation: "Recreation beside and/or in the water"
    },
    {id: 26, siteName: "Nohoanga", aliases: [], explanation: "Sitting place"},
    {id: 27, siteName: "Pā", aliases: [], explanation: "Fortified village"},
    {id: 28, siteName: "Pā harakeke", aliases: [], explanation: "Flax bush, metaphor for whānau"},
    {id: 29, siteName: "Pā tuna", aliases: [], explanation: "Eel weir"},
    {id: 30, siteName: "Papa kāinga", aliases: [], explanation: "Original home"},
    {id: 31, siteName: "Pātaka kai", aliases: [], explanation: "Pantry, food storage"},
    {id: 32, siteName: "Pūkengatanga", aliases: [], explanation: "Knowledge"},
    {id: 33, siteName: "Puna raranga", aliases: [], explanation: "Source of weaving material"},
    {id: 34, siteName: "Puna rongoā", aliases: [], explanation: "Source of medicinal plants"},
    {id: 35, siteName: "Puna uku", aliases: [], explanation: "Source of clay"},
    {id: 36, siteName: "Puni", aliases: [], explanation: "Stopover camp"},
    {id: 37, siteName: "Pure", aliases: [], explanation: "Purification"},
    {id: 38, siteName: "Raranga", aliases: [], explanation: "Weaving"},
    {id: 39, siteName: "Rohenga", aliases: [], explanation: "Boundary"},
    {id: 40, siteName: "Rongoā", aliases: [], explanation: "Traditional healing plants"},
    {id: 41, siteName: "Tanga i te kawa", aliases: [], explanation: "Place of ritual"},
    {id: 42, siteName: "Taniwha", aliases: [], explanation: "Water spirit (guardian)"},
    {id: 43, siteName: "Tārai waka", aliases: [], explanation: "Canoe building"},
    {id: 44, siteName: "Taunga ika", aliases: [], explanation: "Fishing ground"},
    {id: 45, siteName: "Tauranga waka", aliases: [], explanation: "Canoe landing place"},
    {id: 46, siteName: "Te Ara o Kupe", aliases: [], explanation: "The path of Kupe"},
    {id: 47, siteName: "Te Ara o Te Rauparaha", aliases: [], explanation: "The path of Te Rauparaha"},
    {id: 48, siteName: "Tohi", aliases: [], explanation: "Ritual ceremony performed over a child in flowing water"},
    {id: 49, siteName: "Tohu ahurea", aliases: [], explanation: "Traditional value/symbol"},
    {id: 50, siteName: "Tohu moana", aliases: [], explanation: "Marker"},
    {id: 51, siteName: "Tohu tūpuna", aliases: [], explanation: "Ancestral marker"},
    {id: 52, siteName: "Tohu whenua", aliases: [], explanation: "Marker"},
    {id: 53, siteName: "Ūkaipōtanga", aliases: [], explanation: "Source of sustenance, real home"},
    {id: 54, siteName: "Urupā", aliases: [], explanation: "Burial ground"},
    {id: 55, siteName: "Wāhi ahurea", aliases: [], explanation: "Traditional place"},
    {id: 56, siteName: "Wāhi hapori", aliases: [], explanation: "Community place"},
    {id: 57, siteName: "Wāhi horoi", aliases: [], explanation: "Washing place"},
    {id: 58, siteName: "Wāhi kauhoe", aliases: [], explanation: "Swimming place"},
    {id: 59, siteName: "Wāhi kaukau", aliases: [], explanation: "Bathing place"},
    {id: 60, siteName: "Wāhi mahara/maumahara", aliases: [], explanation: "Memorial place"},
    {id: 61, siteName: "Wāhi pakanga", aliases: [], explanation: "Battle ground"},
    {id: 62, siteName: "Wāhi tapu", aliases: [], explanation: "Sacred place"},
    {id: 63, siteName: "Wāhi tūpuna/tīpuna", aliases: ["wahi tipūna"], explanation: "Significant ancestral place"},
    {id: 64, siteName: "Wāhi Whakahaumanu", aliases: [], explanation: "Place of healing and restoration"},
    {id: 65, siteName: "Wāhi Whakarite", aliases: [], explanation: "Place of organising"},
    {id: 66, siteName: "Wai māori", aliases: [], explanation: "Fresh water"},
    {id: 67, siteName: "Wai ora", aliases: [], explanation: "Water utilised for healing"},
    {id: 68, siteName: "Wai tai", aliases: [], explanation: "Sea water"},
    {id: 69, siteName: "Waka", aliases: [], explanation: "Canoe"},
    {id: 70, siteName: "Waka ama", aliases: [], explanation: "Outrigger canoe"},
    {id: 71, siteName: "Whakatupu kai", aliases: [], explanation: "Food growing area"},
    {
        id: 72,
        siteName: "Whakawātea",
        aliases: [],
        explanation: "To clear, free, dislodge, purge, get rid of. Māori use of water to restore spiritual and emotional well-being. Wāhi Whakawātea – places where water is utilised in this way."
    },
    {id: 73, siteName: "Whanaungatanga", aliases: [], explanation: "Relationship"}
]

export default siteNames