-- This script creates tables that match the shape of what will be generated by DBT.
-- This is just to allow JOOQ to generate classes before DBT has run
CREATE TABLE IF NOT EXISTS plans
(
  id                            BIGINT,
  council_id                    INTEGER,
  source_id                     TEXT,
  name                          TEXT,
  default_surface_water_limit   TEXT,
  default_groundwater_limit     TEXT,
  default_flow_management_site  TEXT,
  default_flow_management_limit TEXT
);

CREATE TABLE IF NOT EXISTS water_allocations_by_area
(
  area_id           VARCHAR,
  allocation_amount NUMERIC
);

CREATE TABLE IF NOT EXISTS plan_regions
(
  id                            BIGINT,
  plan_id                       BIGINT,
  source_id                     TEXT,
  name                          TEXT,
  boundary                      geometry,
  default_surface_water_limit   TEXT,
  default_groundwater_limit     TEXT,
  default_flow_management_site  TEXT,
  default_flow_management_limit TEXT,
  reference_url                 TEXT
);

CREATE TABLE IF NOT EXISTS flow_measurement_sites
(
  plan_region_id BIGINT,
  id             BIGINT,
  source_id      TEXT,
  name           TEXT,
  location       geometry
);

CREATE TABLE IF NOT EXISTS flow_limits
(
  plan_region_id      BIGINT,
  id                  BIGINT,
  source_id           TEXT,
  minimum_flow        INTEGER,
  measured_at_site_id BIGINT,
  boundary            geometry
);

CREATE TABLE IF NOT EXISTS groundwater_limits
(
  plan_region_id   BIGINT,
  id               BIGINT,
  source_id        TEXT,
  name             TEXT,
  allocation_limit INTEGER
);

CREATE TABLE IF NOT EXISTS surface_water_limits
(
  id                            BIGINT,
  plan_region_id                BIGINT,
  source_id                     TEXT,
  parent_surface_water_limit_id BIGINT,
  name                          TEXT,
  allocation_limit              INTEGER,
  boundary                      geometry
);

CREATE TABLE IF NOT EXISTS groundwater_areas
(
  groundwater_limit_id BIGINT,
  id                   BIGINT,
  source_id            TEXT,
  category             TEXT,
  depth                TEXT,
  depletion_limit_id   BIGINT,
  boundary             geometry
);

CREATE TABLE IF NOT EXISTS water_allocation_and_usage_by_area
(
  date                  DATE,
  area_id               VARCHAR,
  allocation_plan       NUMERIC,
  allocation_daily      NUMERIC,
  allocation_daily_used NUMERIC,
  daily_usage           NUMERIC
);

CREATE TABLE council_plan_boundaries
(
  council_id INTEGER                                NOT NULL REFERENCES councils,
  source_id  VARCHAR                                NOT NULL,
  boundary   geometry                               NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (council_id, source_id)
);

CREATE TABLE council_plan_boundary_rec2_data
(
  council_id INTEGER                                NOT NULL REFERENCES councils,
  source_id  VARCHAR                                NOT NULL,
  boundary   geometry                               NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (council_id, source_id)
);
