-- UPDATE freshwater_management_units
-- SET implementation_ideas = '<ul><li>Consider wetlands for water quality treatment before discharges reach the stream</li>
-- <li>Setbacks from depressions and waterways should be necessary for intensive land uses including winter grazing and winter cropping</li>
-- <li>Riparian planting should be undertaken in strategic spots, including to provide shade to help improve periphytn and macrophyte problems</li>
-- <li>Good management of stock access to streambanks and of winter grazing may prove important in this catchment</li></ul>'
-- WHERE freshwater_management_units.fmu_name1 = 'Parkvale Stream';
