INSERT INTO
  sites (id, siteid_hilltop, NAME, geom)
VALUES
  (
    1,
    434,
    'Hutt River at Birchville',
    ST_GeomFromText ('POINT(175.09076014 -41.10017595)', 4326)
  ),
  (
    2,
    454,
    'Hutt River at Kaitoke',
    ST_GeomFromText ('POINT(175.19123118 -41.05101129)', 4326)
  ),
  (
    3,
    597,
    'Kopuaranga at Palmers Bridge',
    ST_GeomFromText ('POINT(175.67185573 -40.81893375)', 4326)
  ),
  (
    4,
    706,
    'Mangaone Stream at Ratanui',
    ST_GeomFromText ('POINT(175.15669569 -40.82742334)', 4326)
  ),
  (
    5,
    758,
    'Mangatarere River at Gorge',
    ST_GeomFromText ('POINT(175.51186713 -40.93499383)', 4326)
  ),
  (
    6,
    978,
    'Orongorongo River at Truss Bridge',
    ST_GeomFromText ('POINT(175.0326634 -41.29704076)', 4326)
  ),
  (
    7,
    1012,
    'Otaki River at Pukehinau',
    ST_GeomFromText ('POINT(175.19957526 -40.8220466)', 4326)
  ),
  (
    8,
    1045,
    'Otukura Stream at Weir',
    ST_GeomFromText ('POINT(175.36738907 -41.18728715)', 4326)
  ),
  (
    9,
    1093,
    'Papawai Stream at Fabians Road',
    ST_GeomFromText ('POINT(175.47431592 -41.09518572)', 4326)
  ),
  (
    10,
    1136,
    'Parkvale Stream at Renalls Weir',
    ST_GeomFromText ('POINT(175.54166084 -41.07801993)', 4326)
  ),
  (
    11,
    1518,
    'Ruamahanga River at Waihenga Bridge',
    ST_GeomFromText ('POINT(175.43999678 -41.19685836)', 4326)
  ),
  (
    12,
    1521,
    'Ruamahanga River at Wardells',
    ST_GeomFromText ('POINT(175.67236373 -41.00481677)', 4326)
  ),
  (
    13,
    2368,
    'Tauherenikau at Gorge',
    ST_GeomFromText ('POINT(175.35741926 -41.06814004)', 4326)
  ),
  (
    14,
    2528,
    'Waikanae River at Water Treatment Plant',
    ST_GeomFromText ('POINT(175.07274447 -40.88809773)', 4326)
  ),
  (
    15,
    2559,
    'Waingawa River at Kaituna',
    ST_GeomFromText ('POINT(175.5229277 -40.88669021)', 4326)
  ),
  (
    16,
    2588,
    'Wainuiomata River at Leonard Wood Park',
    ST_GeomFromText ('POINT(174.94738309 -41.28400515)', 4326)
  ),
  (
    17,
    2589,
    'Wainuiomata River at Manuka Track',
    ST_GeomFromText ('POINT(175.00892684 -41.25677265)', 4326)
  ),
  (
    18,
    2609,
    'Waiohine River at Gorge',
    ST_GeomFromText ('POINT(175.40011859 -41.01636817)', 4326)
  ),
  (
    19,
    2634,
    'Waipoua River at Mikimiki Bridge',
    ST_GeomFromText ('POINT(175.61744894 -40.84517651)', 4326)
  ),
  (
    20,
    2666,
    'Waitohu Stream at Water Supply Intake',
    ST_GeomFromText ('POINT(175.21423898 -40.76666669)', 4326)
  );

INSERT INTO
  minimum_flow_limits (
    plan_description,
    plan_management_point_name,
    plan_minimum_flow_value,
    plan_minimum_flow_unit,
    site_id,
    plan_table,
    plan_version,
    hydro_id,
    excluded_hydro_ids
  )
VALUES
  (
    'Upstream of Belvedere road bridge',
    'Mangatarere River at Gorge',
    240,
    'L/s',
    5,
    7.1,
    'final appeals version 2022',
    257409,
    '{}'
  ),
  (
    'Between the confluence with the Waiohine River and the Belvedere Road bridge',
    'Mangatarere River at Gorge',
    200,
    'L/s',
    5,
    7.1,
    'final appeals version 2022',
    258982,
    '{257409}'
  ),
  (
    'Kopuaranga River upstream of the confluence with the Ruamāhanga River',
    'Palmers',
    270,
    'L/s',
    3,
    7.1,
    'final appeals version 2022',
    254602,
    '{}'
  ),
  (
    'Waipoua River upstream of the confluence with the Ruamāhanga River',
    'Mikimiki Bridge',
    250,
    'L/s',
    19,
    7.1,
    'final appeals version 2022',
    256291,
    '{}'
  ),
  (
    'Waingawa River upstream of the confluence with the Ruamāhanga River',
    'Kaituna',
    1100,
    'L/s',
    15,
    7.1,
    'final appeals version 2022',
    257578,
    '{256291, 254602}'
  ),
  (
    'Parkvale Stream upstream of the confluence with the Ruamāhanga River',
    'Renalls Weir recorder',
    100,
    'L/s',
    10,
    7.1,
    'final appeals version 2022',
    259497,
    '{}'
  ),
  (
    'Waiohine River upstream of the confluence with the Ruamāhanga River',
    'Gorge recorder',
    2300,
    'L/s',
    18,
    7.1,
    'final appeals version 2022',
    260015,
    '{258982}'
  ),
  (
    'Papawai Stream upstream of the confluence with the Ruamāhanga River',
    'Fabians Road recorder',
    180,
    'L/s',
    9,
    7.1,
    'final appeals version 2022',
    260343,
    '{}'
  ),
  (
    'Upper and Middle Ruamāhanga River upstream of the confluence with the Waiohine River',
    'Wardells ',
    2400,
    'L/s',
    12,
    7.1,
    'final appeals version 2022',
    259960,
    '{259497, 257578, 256291, 254602}'
  ),
  (
    'Otukura Stream upstream of the confluence with Dock/Stonestead Creek',
    'Weir recorder ',
    95,
    'L/s',
    8,
    7.1,
    'final appeals version 2022',
    262397,
    '{}'
  ),
  (
    'Tauherenikau River upstream of Lake Wairarapa',
    'Gorge recorder',
    1100,
    'L/s',
    13,
    7.1,
    'final appeals version 2022',
    261930,
    '{}'
  ),
  (
    'Lower Ruamāhanga River between the boundary with the coastal marine area and the Waiohine River confluence ',
    'Waihenga recorder',
    8500,
    'L/s',
    11,
    7.1,
    'final appeals version 2022',
    267143,
    '{260015, 261930, 262397, 260343, 258982, 259960}'
  ),
  (
    'Te Awa Kairangi/Hutt River Upstream of the confluence with the Pakuratahi River',
    'Kaitoke water supply intake',
    600,
    'L/s',
    2,
    8.1,
    'final appeals version 2022',
    258639,
    '{}'
  ),
  (
    'Te Awa Kairangi/Hutt River Downstream of the confluence with the Pakuratahi River',
    'Birchville recorder ',
    1200,
    'L/s',
    1,
    8.1,
    'final appeals version 2022',
    263323,
    '{258639}'
  ),
  (
    'Wainuiomata River Between Manuka Track and the confluence with Georges Creek ',
    'Manuka recorder',
    100,
    'L/s',
    17,
    8.1,
    'final appeals version 2022',
    264063,
    '{}'
  ),
  (
    'Wainuiomata River Between Georges Creek and the boundary of the coastal marine area',
    'Leonard Wood Park recorder',
    300,
    'L/s',
    16,
    8.1,
    'final appeals version 2022',
    267323,
    '{264063}'
  ),
  (
    'Orongorongo River upstream of the boundary with the coastal marine area',
    'Truss Bridge recorder',
    100,
    'L/s',
    6,
    8.1,
    'final appeals version 2022',
    267384,
    '{}'
  ),
  (
    'Waitohu Stream upstream of the coastal marine area boundary',
    'KCDC Water Supply Intake recorder ',
    140,
    'L/s',
    20,
    10.1,
    'final appeals version 2022',
    249434,
    '{}'
  ),
  (
    'Ōtaki River upstream of the coastal marine area boundary',
    'Pukehinau recorder',
    2550,
    'L/s',
    7,
    10.1,
    'final appeals version 2022',
    250291,
    '{}'
  ),
  (
    'Mangaone Stream upstream of the coastal marine area boundary',
    'Ratanui recorder',
    22,
    'L/s',
    4,
    10.1,
    'final appeals version 2022',
    251029,
    '{}'
  ),
  (
    'Waikanae River upstream of the coastal marine area boundary ',
    'WTP recorder',
    750,
    'L/s',
    14,
    10.1,
    'final appeals version 2022',
    253589,
    '{}'
  );

INSERT INTO
  allocation_amounts (
    id,
    take_type,
    management_unit_type,
    area_description,
    surfacewater_subunit_name,
    parent_surfacewatersubunit_id,
    hydro_id,
    excluded_hydro_ids,
    allocation_amount,
    allocation_amount_unit,
    consented_allocation_greater_than_allocation_amount,
    catchment_management_unit,
    plan_version,
    plan_table
  )
VALUES
  (
    1,
    'GROUNDWATER',
    NULL,
    'Te Ore Ore Category B groundwater',
    NULL,
    20,
    NULL,
    NULL,
    480000,
    'm³/year',
    TRUE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    2,
    'GROUNDWATER',
    NULL,
    'Waingawa Category B groundwater and Waingawa Category C groundwater',
    NULL,
    19,
    NULL,
    NULL,
    1900000,
    'm³/year',
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    3,
    'GROUNDWATER',
    NULL,
    'Ruamāhanga Category B groundwater and Ruamāhanga Category C groundwater',
    NULL,
    16,
    NULL,
    NULL,
    3550000,
    'm³/year',
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    4,
    'GROUNDWATER',
    NULL,
    'Fernhill-Tiffen Category C groundwater',
    NULL,
    NULL,
    NULL,
    NULL,
    1200000,
    'm³/year',
    FALSE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    5,
    'GROUNDWATER',
    NULL,
    'Taratahi Category B groundwater and Taratahi Category C groundwater',
    NULL,
    19,
    NULL,
    NULL,
    1400000,
    'm³/year',
    FALSE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    6,
    'GROUNDWATER',
    NULL,
    'Parkvale Category B groundwater and Parkvale Category C groundwater (confined)',
    NULL,
    21,
    NULL,
    NULL,
    350000,
    'm³/year',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    7,
    'GROUNDWATER',
    NULL,
    'Parkvale Category B groundwater and Parkvale Category C groundwater (unconfined)',
    NULL,
    21,
    NULL,
    NULL,
    1550000,
    'm³/year',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    8,
    'GROUNDWATER',
    NULL,
    'Mangatarere Category B groundwater and Mangatarere Category C groundwater',
    NULL,
    23,
    NULL,
    NULL,
    2300000,
    'm³/year',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    9,
    'GROUNDWATER',
    NULL,
    'Tauherenikau Category B groundwater',
    NULL,
    31,
    NULL,
    NULL,
    6600000,
    'm³/year',
    TRUE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    10,
    'GROUNDWATER',
    NULL,
    'Lower Ruamāhanga Category B groundwater',
    NULL,
    28,
    NULL,
    NULL,
    3300000,
    'm³/year',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    11,
    'GROUNDWATER',
    NULL,
    'Lake Category B groundwater and Lake Category C groundwater',
    NULL,
    29,
    NULL,
    NULL,
    6750000,
    'm³/year',
    TRUE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    12,
    'GROUNDWATER',
    NULL,
    'Huangarua Category B groundwater',
    NULL,
    27,
    NULL,
    NULL,
    650000,
    'm³/year',
    TRUE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    13,
    'GROUNDWATER',
    NULL,
    'Martinborough Category C groundwater',
    NULL,
    NULL,
    NULL,
    NULL,
    800000,
    'm³/year',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    14,
    'GROUNDWATER',
    NULL,
    'Dry River Category B groundwater',
    NULL,
    NULL,
    NULL,
    NULL,
    650000,
    'm³/year',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    15,
    'GROUNDWATER',
    NULL,
    'Onoke Category C groundwater',
    NULL,
    NULL,
    NULL,
    NULL,
    2100000,
    'm³/year',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.5
  ),
  (
    16,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Ruamāhanga River and tributaries, upstream of (but not including) the confluence with the Lake Wairarapa outflow, and all Category A groundwater and Category B groundwater (stream depletion) identified in the catchment management sub-units below in Table 7.3',
    'Ruamāhanga River and tributaries, upstream of (but not including) the confluence with the Lake Wairarapa outflow',
    NULL,
    265439,
    '{}',
    7430,
    'L/s',
    FALSE,
    'Ruamāhanga River catchment above the Lake Wairarapa outflow',
    'final appeals version 2022',
    7.3
  ),
  (
    17,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Kopuaranga River and tributaries, Category A groundwater and Upper Ruamāhanga Category B groundwater(stream depletion)',
    'Kopuaranga River and tributaries',
    NULL,
    254602,
    '{}',
    180,
    'L/s',
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    18,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Waipoua River and tributaries, Category A groundwater and Upper Ruamāhanga or Waingawa Category B groundwater (stream depletion)',
    'Waipoua River and tributaries',
    NULL,
    256291,
    '{}',
    145,
    'L/s',
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    19,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Waingawa River and tributaries, Waingawa Category A groundwater) and Taratahi or Waingawa Category B groundwater (stream depletion)',
    'Waingawa River and tributaries',
    NULL,
    257578,
    '{}',
    920,
    'L/s',
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    20,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Ruamāhanga River and tributaries upstream of the confluence with the Waingawa River, Upper Ruamāhanga Category A groundwater and Waingawa, Te Ore Ore or Upper Ruamāhanga Category B groundwater (stream depletion), excluding all the above catchment management subunits in the Ruamāhanga catchment (above this row in Table 7.3)',
    'Ruamāhanga River and tributaries upstream of the confluence with the Waingawa River',
    NULL,
    257579,
    '{256291,254602}',
    NULL,
    NULL,
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    21,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Parkvale Stream and tributaries, and Taratahi or Parkvale Category B groundwater (stream depletion)',
    'Parkvale Stream and tributaries',
    NULL,
    259497,
    '{}',
    40,
    'L/s',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    22,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Booths Creek and tributaries and Parkvale, Mangatarere or Taratahi Category B groundwater (stream depletion)',
    'Booths Creek and tributaries',
    NULL,
    259523,
    '{}',
    25,
    'L/s',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    23,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Mangatarere Stream and tributaries, Mangatarere Category A groundwater and Mangatarere Category B groundwater (stream depletion)',
    'Mangatarere Stream and tributaries',
    NULL,
    257905,
    '{}',
    110,
    'L/s',
    FALSE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    24,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Waiohine River and tributaries (excluding Mangatarere Stream and tributaries) Waiohine Category A groundwater) and Mangatarere Category B groundwater (stream depletion)',
    'Waiohine River and tributaries',
    NULL,
    260015,
    '{258982}',
    1590,
    'L/s',
    FALSE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    25,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Papawai Stream and tributaries and Waiohine Category A groundwater',
    'Papawai Stream and tributaries',
    NULL,
    260343,
    '{}',
    105,
    'L/s',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    26,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Ruamāhanga River and tributaries upstream of the confluence with the Papawai Stream, and Middle Ruamāhanga Category A groundwater excluding all the above catchment management sub-units in the Ruamāhanga catchment (above this row in Table 7.3)',
    'Ruamāhanga River and tributaries upstream of the confluence with the Papawai Stream',
    NULL,
    260344,
    '{260015,259523,259497,257579,257578}',
    NULL,
    NULL,
    FALSE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    27,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Huangarua River and tributaries and Huangarua Category A groundwater and Huangarua Category B groundwater (stream depletion)',
    'Huangarua River and tributaries',
    NULL,
    262787,
    '{}',
    NULL,
    NULL,
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    28,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Lower Ruamāhanga River and tributaries upstream of (but not including) the confluence with the Lake Wairarapa outflow, and Lower Ruamāhanga Category A groundwater and Lake Category B groundwater (stream depletion) excluding all the above catchment management sub-units in the Ruamāhanga catchment (above this row in Table 7.3)',
    'Lower Ruamāhanga River and tributaries upstream of (but not including) the confluence with the Lake Wairarapa outflow',
    NULL,
    265439,
    '{262787,260343,260344}',
    NULL,
    NULL,
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    29,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Lake Wairarapa and tributaries above the confluence of the Lake Wairarapa outflow with the Ruamāhanga River, and Tauherenikau Category A groundwater and Lake or Tauherenikau Category B groundwater (stream depletion)',
    'Lake Wairarapa and tributaries above the confluence of the Lake Wairarapa outflow with the Ruamāhanga River',
    NULL,
    265528,
    '{}',
    1800,
    'L/s',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.4
  ),
  (
    30,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Otukura Stream and tributaries above (but not including) the confluence with Dock/Stonestead Creek and Tauherenikau Category B groundwater (stream depletion)',
    'Otukura Stream and tributaries above (but not including) the confluence with Dock/Stonestead Creek',
    NULL,
    262349,
    '{}',
    30,
    'L/s',
    TRUE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.4
  ),
  (
    31,
    'SURFACE_WATER',
    'MANAGEMENT_SUB_UNIT',
    'Tauherenikau River and tributaries, and Tauherenikau Category A groundwater and Tauherenikau Category B groundwater (stream depletion)',
    'Tauherenikau River and tributaries',
    NULL,
    261974,
    '{}',
    NULL,
    NULL,
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.4
  ),
  (
    32,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Te Awa Kairangi/Hutt River and tributaries, Upper Hutt or Lower Hutt Category A groundwater and Upper or Lower Hutt Category B groundwater (stream depletion) in the catchment management units shown in Figures 8.1 and 8.2',
    'Te Awa Kairangi/Hutt River and tributaries',
    NULL,
    263323,
    '{}',
    NULL,
    NULL,
    FALSE,
    'Te Awa Kairangi/Hutt River',
    'final appeals version 2022',
    8.2
  ),
  (
    33,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Wainuiomata River and tributaries',
    'Wainuiomata River and tributaries',
    NULL,
    267323,
    '{}',
    180,
    'L/s',
    FALSE,
    'Wainuiomata River',
    'final appeals version 2022',
    8.2
  ),
  (
    34,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Orongorongo River and tributaries',
    'Orongorongo River and tributaries',
    NULL,
    267384,
    '{}',
    95,
    'L/s',
    FALSE,
    'Orongorongo River',
    'final appeals version 2022',
    8.2
  ),
  (
    35,
    'GROUNDWATER',
    NULL,
    'Upper Hutt Category B groundwater and Upper Hutt Category C groundwater',
    NULL,
    32,
    NULL,
    NULL,
    770000,
    'm³/year',
    FALSE,
    'Wellington Harbour and Hutt Valley Whaitua',
    'final appeals version 2022',
    8.3
  ),
  (
    36,
    'GROUNDWATER',
    NULL,
    'Lower Hutt Category B groundwater',
    NULL,
    32,
    NULL,
    NULL,
    36500000,
    'm³/year',
    FALSE,
    'Wellington Harbour and Hutt Valley Whaitua',
    'final appeals version 2022',
    8.3
  ),
  (
    37,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Waitohu Stream and tributaries, Waitohu Category A groundwater and Ōtaki Category B groundwater (stream depletion)',
    'Waitohu Stream and tributaries',
    NULL,
    249434,
    '{}',
    NULL,
    NULL,
    FALSE,
    'Waitohu Stream and tributaries',
    'final appeals version 2022',
    10.2
  ),
  (
    38,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Ōtaki River and tributaries, Ōtaki Category A groundwater and Ōtaki or Te Horo Category B groundwater (stream depletion)',
    'Ōtaki River and tributaries',
    NULL,
    250291,
    '{}',
    NULL,
    NULL,
    FALSE,
    'Ōtaki',
    'final appeals version 2022',
    10.2
  ),
  (
    39,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Mangaone Stream and tributaries, Te Horo Category B groundwater (stream depletion)',
    'Mangaone Stream and tributaries',
    NULL,
    251029,
    '{}',
    24,
    'L/s',
    FALSE,
    'Mangaone Stream and tributaries',
    'final appeals version 2022',
    10.2
  ),
  (
    40,
    'SURFACE_WATER',
    'MANAGEMENT_UNIT',
    'Waikanae River and tributaries, Waikanae Category A groundwater and Waikanae Category B groundwater (stream depletion)',
    'Waikanae River and tributaries',
    NULL,
    253589,
    '{}',
    NULL,
    NULL,
    FALSE,
    'Waikanae River and tributaries',
    'final appeals version 2022',
    10.2
  ),
  (
    41,
    'GROUNDWATER',
    NULL,
    'Raumati Category B groundwater',
    NULL,
    NULL,
    NULL,
    NULL,
    1229000,
    'm³/year',
    FALSE,
    'Raumati',
    'final appeals version 2022',
    10.3
  ),
  (
    42,
    'GROUNDWATER',
    NULL,
    'Waikanae Category B groundwater',
    NULL,
    40,
    NULL,
    NULL,
    2710000,
    'm³/year',
    FALSE,
    'Waikanae',
    'final appeals version 2022',
    10.3
  ),
  (
    43,
    'GROUNDWATER',
    NULL,
    'Te Horo Category B groundwater',
    NULL,
    38,
    NULL,
    NULL,
    1620000,
    'm³/year',
    FALSE,
    'Te Horo',
    'final appeals version 2022',
    10.3
  ),
  (
    44,
    'GROUNDWATER',
    NULL,
    'Waitohu Category B groundwater',
    NULL,
    37,
    NULL,
    NULL,
    1080000,
    'm³/year',
    FALSE,
    'Waitohu',
    'final appeals version 2022',
    10.3
  ),
  (
    45,
    'GROUNDWATER',
    NULL,
    'Waiohine Category A groundwater',
    NULL,
    25,
    NULL,
    NULL,
    105,
    'L/s',
    TRUE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    46,
    'GROUNDWATER',
    NULL,
    'Middle Ruamāhanga Category A groundwater',
    NULL,
    26,
    NULL,
    NULL,
    1240,
    'L/s',
    FALSE,
    'Middle Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    47,
    'GROUNDWATER',
    NULL,
    'Huangarua Category A groundwater',
    NULL,
    27,
    NULL,
    NULL,
    110,
    'L/s',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    48,
    'GROUNDWATER',
    NULL,
    'Lower Ruamāhanga Category A groundwater',
    NULL,
    28,
    NULL,
    NULL,
    1370,
    'L/s',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.3
  ),
  (
    49,
    'GROUNDWATER',
    NULL,
    'Tauherenikau Category A groundwater and Tauherenikau Category B groundwater (stream depletion)',
    NULL,
    31,
    NULL,
    NULL,
    410,
    'L/s',
    FALSE,
    'Lower Ruamāhanga',
    'final appeals version 2022',
    7.4
  ),
  (
    50,
    'GROUNDWATER',
    NULL,
    'Upper Hutt or Lower Hutt Category A groundwater and Upper or Lower Hutt Category B groundwater (stream depletion)',
    NULL,
    32,
    NULL,
    NULL,
    2140,
    'L/s',
    FALSE,
    'Te Awa Kairangi/Hutt River',
    'final appeals version 2022',
    8.2
  ),
  (
    51,
    'GROUNDWATER',
    NULL,
    'Waitohu Category A groundwater and Ōtaki Category B groundwater (stream depletion)',
    NULL,
    37,
    NULL,
    NULL,
    45,
    'L/s',
    FALSE,
    'Waitohu Stream and tributaries',
    'final appeals version 2022',
    10.2
  ),
  (
    52,
    'GROUNDWATER',
    NULL,
    'Ōtaki Category A groundwater and Ōtaki or Te Horo Category B groundwater (stream depletion)',
    NULL,
    38,
    NULL,
    NULL,
    590,
    'L/s',
    FALSE,
    'Ōtaki',
    'final appeals version 2022',
    10.2
  ),
  (
    53,
    'GROUNDWATER',
    NULL,
    'Waikanae Category A groundwater and Waikanae Category B groundwater (stream depletion)',
    NULL,
    40,
    NULL,
    NULL,
    220,
    'L/s',
    FALSE,
    'Waikanae River and tributaries',
    'final appeals version 2022',
    10.2
  ),
  (
    54,
    'GROUNDWATER',
    NULL,
    'Upper Ruamāhanga Category A groundwater and Waingawa, Te Ore Ore or Upper Ruamāhanga Category B groundwater (stream depletion)',
    NULL,
    20,
    NULL,
    NULL,
    1200,
    'L/s',
    FALSE,
    'Upper Ruamāhanga',
    'final appeals version 2022',
    7.3
  );
