CREATE TABLE council_plan_documents
(
  id         SERIAL PRIMARY KEY,
  council_id INTEGER                                NOT NULL UNIQUE REFERENCES councils,
  source_id  VARCHAR                                NOT NULL,
  document   jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  UNIQUE (council_id, source_id)
);

CREATE TABLE council_plan_boundary_geom_source
(
  council_id INTEGER                                NOT NULL REFERENCES councils,
  source_id  VARCHAR                                NOT NULL,
  boundary   geometry                               NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (council_id, source_id)
);

CREATE TABLE council_plan_boundary_geojson_source
(
  council_id INTEGER                                NOT NULL REFERENCES councils,
  source_id  VARCHAR                                NOT NULL,
  url        VARCHAR                                NOT NULL,
  feature_id VARCHAR                                NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (council_id, source_id)
);

CREATE TABLE council_plan_boundary_geojson_data
(
  council_id INTEGER                                NOT NULL REFERENCES councils,
  source_id  VARCHAR                                NOT NULL,
  boundary   geometry                               NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (council_id, source_id)
);

CREATE TABLE council_plan_boundary_rec2_source
(
  council_id         INTEGER                                NOT NULL REFERENCES councils,
  source_id          VARCHAR                                NOT NULL,
  hydro_ids          INTEGER[]                              NOT NULL,
  excluded_hydro_ids INTEGER[]                              NOT NULL,
  created_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at         TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (council_id, source_id)
);


CREATE TABLE water_allocations
(
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id           VARCHAR                                            NOT NULL,
  allocation_plan   NUMERIC                                            NOT NULL,
  ingest_id         VARCHAR                                            NOT NULL,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE                           NOT NULL,
  source_id         VARCHAR                                            NOT NULL,
  consent_id        VARCHAR                                            NOT NULL,
  status            VARCHAR                                            NOT NULL,
  is_metered        BOOLEAN                                            NOT NULL,
  allocation_daily  NUMERIC                                            NOT NULL,
  allocation_yearly NUMERIC                                            NOT NULL,
  meters            CHARACTER VARYING[]                                NOT NULL
    CONSTRAINT water_allocations_meters_check
      CHECK (array_position(meters, NULL::CHARACTER VARYING) IS NULL),
  effective_from    TIMESTAMP WITH TIME ZONE                           NOT NULL,
  effective_to      TIMESTAMP WITH TIME ZONE
);

CREATE UNIQUE INDEX water_allocations_source_id_effective_to_idx
  ON water_allocations (source_id)
  WHERE (effective_to IS NULL);
