CREATE TABLE
  council_boundaries (
    id INTEGER NOT NULL,
    NAME VARCHAR NOT NULL,
    geom GEOMETRY NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  );

CREATE TABLE
  whaitua_boundaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR NOT NULL,
    geom GEOMETRY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  );

CREATE TABLE
  sites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    siteid_hilltop INTEGER NOT NULL UNIQUE,
    NAME VARCHAR NOT NULL,
    geom GEOMETRY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  );

CREATE TABLE
  rivers (
    hydro_id INTEGER NOT NULL,
    next_hydro_id INTEGER,
    nz_segment INTEGER NOT NULL,
    is_headwater BOOLEAN NOT NULL,
    stream_order INTEGER NOT NULL,
    geom geometry NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (hydro_id)
  );

CREATE INDEX
  ON rivers USING gist (geom);

CREATE INDEX
  ON rivers (created_at DESC);

CREATE TABLE
  watersheds (
    hydro_id INTEGER NOT NULL,
    nz_segment INTEGER NOT NULL,
    geom geometry NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (hydro_id)
  );

CREATE INDEX
  ON watersheds USING gist (geom);

CREATE INDEX
  ON watersheds (created_at DESC);

CREATE TABLE
  catchments (
    id INTEGER NOT NULL,
    hydro_id INTEGER NOT NULL,
    excluded_hydro_ids INTEGER[] NOT NULL,
    geom geometry NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  );

CREATE INDEX
  ON catchments (created_at DESC);

CREATE TABLE
  minimum_flow_limits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    plan_description VARCHAR NOT NULL,
    plan_management_point_name VARCHAR NOT NULL,
    plan_minimum_flow_value NUMERIC NOT NULL,
    plan_minimum_flow_unit VARCHAR NOT NULL,
    siteid_hilltop INTEGER NOT NULL,
    plan_table NUMERIC NOT NULL,
    plan_version VARCHAR NOT NULL,
    hydro_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (siteid_hilltop) REFERENCES sites (siteid_hilltop),
    PRIMARY KEY (id)
  );

CREATE INDEX
  ON minimum_flow_limits (created_at DESC);

CREATE TABLE
  groundwater_zones (
    id VARCHAR NOT NULL,
    NAME VARCHAR NOT NULL,
    category VARCHAR NOT NULL,
    DEPTH VARCHAR NOT NULL,
    notes VARCHAR NOT NULL,
    geom GEOMETRY NOT NULL,
    catchment_id INTEGER,
    site_id INTEGER,
    groundwater_zone VARCHAR UNIQUE,
    PRIMARY KEY (id)
  );

CREATE TABLE
  allocation_amounts (
    id INTEGER UNIQUE,
    take_type VARCHAR NOT NULL,
    management_unit_type VARCHAR NULL,
    area_description VARCHAR NULL,
    surfacewater_subunit_name VARCHAR NULL,
    parent_surfacewatersubunit_id INTEGER NULL,
    hydro_id INTEGER,
    excluded_hydro_ids INTEGER[],
    allocation_amount NUMERIC,
    allocation_amount_unit VARCHAR,
    consented_allocation_greater_than_allocation_amount BOOLEAN,
    catchment_management_unit VARCHAR NULL,
    plan_version VARCHAR NULL,
    plan_table NUMERIC NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    groundwaterzone_id INTEGER NULL,
    PRIMARY KEY (id)
  );

CREATE INDEX
  ON allocation_amounts (created_at DESC);

CREATE TABLE
  raw_rec_features_rivers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ingested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA jsonb,
    PRIMARY KEY (id)
  );

CREATE INDEX
  ON raw_rec_features_rivers (ingested_at DESC);

COMMENT
  ON TABLE raw_rec_features_rivers IS 'Store for the REC rivers as RAW GeoJSON features. One Feature per row';

CREATE TABLE
  raw_rec_features_watersheds (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ingested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA jsonb,
    PRIMARY KEY (id)
  );

CREATE INDEX
  ON raw_rec_features_watersheds (ingested_at DESC);

COMMENT
  ON TABLE raw_rec_features_rivers IS 'Store for the REC watersheds as RAW GeoJSON features. One Feature per row';

CREATE TABLE
  raw_rec_rivers_names (
    nz_segment INTEGER NOT NULL,
    river_name VARCHAR NOT NULL,
    ingested_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (nz_segment)
  );

CREATE INDEX
  ON raw_rec_rivers_names (ingested_at DESC);
