CREATE TABLE
  council_boundaries (
    id INTEGER,
    NAME VARCHAR NULL,
    geom GEOMETRY NULL,
    PRIMARY KEY (id)
  );

CREATE TABLE
  whaitua_boundaries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    NAME VARCHAR NULL,
    geom GEOMETRY NULL,
    PRIMARY KEY (id)
  );

CREATE TABLE
  sites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    siteid_hilltop INTEGER UNIQUE,
    NAME VARCHAR,
    geom GEOMETRY,
    PRIMARY KEY (id)
  );

CREATE TABLE
  rivers_catchments (
    hydro_id INTEGER NOT NULL,
    PATH geometry NOT NULL,
    PRIMARY KEY (hydro_id)
  );

CREATE TABLE
  minimum_flow_limits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    plan_description VARCHAR NULL,
    plan_management_point_name VARCHAR NULL,
    plan_minimum_flow_value NUMERIC,
    plan_minimum_flow_unit VARCHAR,
    siteid_hilltop INTEGER NULL,
    plan_table NUMERIC NULL,
    plan_version VARCHAR NULL,
    hydro_id INTEGER NULL,
    FOREIGN KEY (siteid_hilltop) REFERENCES sites (siteid_hilltop),
    PRIMARY KEY (id)
  );

CREATE TABLE
  groundwater_zones (
    id VARCHAR NULL,
    NAME VARCHAR NULL,
    category VARCHAR NULL,
    DEPTH VARCHAR NULL,
    notes VARCHAR NULL,
    geom GEOMETRY NULL,
    catchment_id INTEGER NULL,
    site_id INTEGER NULL,
    groundwater_zone VARCHAR UNIQUE,
    PRIMARY KEY (id)
  );

CREATE TABLE
  allocation_amounts (
    id INTEGER,
    area_description VARCHAR NULL,
    hydro_id INTEGER NULL,
    allocation_amount NUMERIC,
    allocation_amount_unit VARCHAR,
    consented_allocation_greater_than_allocation_amount BOOLEAN,
    catchment_management_unit VARCHAR NULL,
    groundwater_zone VARCHAR,
    plan_version VARCHAR NULL,
    plan_table NUMERIC NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );
