CREATE TABLE raw_rec_features_rivers
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data        jsonb,
    PRIMARY KEY (id)
);

COMMENT ON TABLE raw_rec_features_rivers IS 'Store for the REC rivers as RAW GeoJSON features. One Feature per row';

CREATE TABLE raw_rec_features_watersheds
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ingested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data        jsonb,
    PRIMARY KEY (id)
);

COMMENT ON TABLE raw_rec_features_rivers IS 'Store for the REC watersheds as RAW GeoJSON features. One Feature per row';

CREATE TABLE rivers_processed
(
    hydro_id      INTEGER NOT NULL,
    next_hydro_id INTEGER,
    nz_segment    INTEGER NOT NULL,
    is_headwater  BOOLEAN NOT NULL,
    stream_order  INTEGER NOT NULL,
    path          geometry NOT NULL,
    PRIMARY KEY (hydro_id)
);

CREATE INDEX ON rivers_processed USING gist (path);

CREATE TABLE watersheds_processed
(
    hydro_id   INTEGER NOT NULL,
    nz_segment INTEGER NOT NULL,
    path       geometry NOT NULL,
    PRIMARY KEY (hydro_id)
);

CREATE INDEX ON watersheds_processed USING gist (path);

CREATE TABLE rivers_network
(
    hydro_id         INTEGER NOT NULL,
    parent_hydro_ids INTEGER[],
    tree_hydro_ids   INTEGER[],
    depth            INTEGER,
    PRIMARY KEY (hydro_id)
);

CREATE TABLE rivers_catchments
(
    hydro_id      INTEGER NOT NULL,
    path          geometry NOT NULL,
    PRIMARY KEY (hydro_id)
);