CREATE TABLE
  PUBLIC.sites (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    siteid_hilltop int4 NOT NULL UNIQUE,
    "name" VARCHAR NOT NULL,
    geom PUBLIC.geometry NULL
  );

CREATE TABLE
  PUBLIC.catchments (
    id int4 NOT NULL,
    nzsegment int8 NOT NULL UNIQUE,
    geom PUBLIC.geometry NOT NULL
  );

CREATE TABLE
  PUBLIC.minimum_flow_limits (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    plan_description VARCHAR NULL,
    plan_management_point_name VARCHAR NULL,
    plan_minimum_flow_value NUMERIC NOT NULL,
    plan_minimum_flow_unit VARCHAR NULL,
    siteid_hilltop int4 NULL,
    plan_table_reference VARCHAR NULL,
    plan_version VARCHAR NULL,
    nzsegment int8 NULL,
    CONSTRAINT fk_sites FOREIGN KEY (siteid_hilltop) REFERENCES sites (siteid_hilltop),
    CONSTRAINT fk_catchments FOREIGN KEY (nzsegment) REFERENCES catchments (nzsegment)
  );

CREATE TABLE
  PUBLIC.groundwater_zones (
    id VARCHAR NULL,
    "name" VARCHAR NULL,
    category VARCHAR NULL,
    "depth" VARCHAR NULL,
    notes VARCHAR NULL,
    geom PUBLIC.geometry NULL,
    catchment_id int4 NULL,
    site_id int4 NULL,
    groundwater_zone VARCHAR NOT NULL UNIQUE
  );

CREATE TABLE
  PUBLIC.allocation_amounts (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    area_description VARCHAR NULL,
    category VARCHAR NULL,
    allocation_amount NUMERIC NOT NULL,
    allocation_amount_unit VARCHAR NOT NULL,
    consented_allocation_greater_than_allocation_amount VARCHAR NULL,
    catchment_management_unit VARCHAR NULL,
    groundwater_zone VARCHAR NOT NULL,
    plan_version VARCHAR NULL,
    plan_table VARCHAR NULL
    -- ,CONSTRAINT fk_groundwater_zones FOREIGN KEY (groundwater_zone) REFERENCES groundwater_zones (groundwater_zone)
  );

CREATE TABLE
  PUBLIC.whaitua_boundaries (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR NULL,
    geom PUBLIC.geometry NULL
    
  );


