SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;

CREATE TABLE system_values
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY,
    council_id      INTEGER NULL,
    value_name      VARCHAR NOT NULL,
    value_as_json   JSONB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),

    UNIQUE (council_id, value_name),

    FOREIGN KEY (council_id) REFERENCES councils(id)
);

CREATE INDEX idx_global_values ON system_values (council_id, value_name) WHERE system_values.council_id IS NULL;