CREATE TABLE water_allocations
(
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
  area_id                 VARCHAR NOT NULL UNIQUE,
  amount                  INTEGER NOT NULL,
  last_updated_ingest_id  VARCHAR NOT NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMPTZ NOT NULL,  
  received_at             TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (id)
);
