CREATE TABLE water_allocations
(
  id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
  area_id                 VARCHAR NOT NULL UNIQUE,
  amount                  INTEGER NOT NULL,
  last_updated_ingest_id  VARCHAR NOT NULL,
  created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);
