SET CLIENT_ENCODING TO UTF8;
SET STANDARD_CONFORMING_STRINGS TO ON;

ALTER TABLE tangata_whenua_sites
    ADD COLUMN properties JSONB,
    ADD COLUMN source_name VARCHAR,
    ALTER COLUMN location DROP NOT NULL;