CREATE TABLE tangata_whenua_sites
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    location   VARCHAR  NOT NULL,
    geom       GEOMETRY NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);