version: 2

sources:
  - name: public
    tables:
      - name: raw_rec_features_rivers
        columns:
          - name: id
            data_type: integer
          - name: ingested_at
            data_type: timestamp without time zone
          - name: data
            data_type: jsonb

      - name: raw_rec_features_watersheds
        columns:
          - name: id
            data_type: integer
          - name: ingested_at
            data_type: timestamp without time zone
          - name: data
            data_type: jsonb
