spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest

server:
  compression:
    enabled: true
    mime-types: application/json

ingestApi:
  usersJSON: '{"gw": "test-api-token"}'
  topicReplicas: 1
