spring:
  main:
    banner-mode: off
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json.add.type.headers: false

server:
  compression:
    enabled: true
    mime-types: application/json

ingestApi:
  usersJSON: '{"gw": "test-api-token"}'
  topicReplicas: 1

logging:
  level:
    root: INFO
    nz.govt.eop: INFO
