spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: earliest

server:
  compression:
    enabled: true
    mime-types: application/json

ingestApi:
  usersJSON: '[{"id": "gw", "token": "12345"}]'
  topicReplicas: 1
