spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/eop_dev
    username: postgres
    password: password

server:
  compression:
    enabled: true
    mime-types: application/json