# Config specifically for when application is deployed to AWS.
# this enables pulling in configuration from AWS Secrets manager
spring:
  config:
    import: aws-secretsmanager:EOPManagerDBConfig # When deployed to AWS this will load from the Secrets

logging:
  level:
    io.awspring.cloud: DEBUG
    org.jooq: INFO
