spring:
  application:
    name: manager
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${CONFIG_DATABASE_HOST:localhost}:${CONFIG_DATABASE_PORT:5432}/${CONFIG_DATABASE_NAME:eop_dev}
    username: ${CONFIG_DATABASE_USERNAME:eop_manager_app_user}
    password: ${CONFIG_DATABASE_PASSWORD:password}

  flyway:
    locations: classpath:/db/migration,classpath:/db/migration-dev
    user: ${CONFIG_DATABASE_MIGRATIONS_USERNAME:eop_manager_migrations_user}
    password: ${CONFIG_DATABASE_MIGRATIONS_PASSWORD:password}

  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.json.value.type.method: nz.govt.eop.messages.KafkaMessageTypes.determineTypeFromTopicName
        spring.json.trusted.packages: nz.govt.eop.*
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer


    # These producer settings are used when publishing messages to the DLQ
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # In the situation that a message was received as invalid JSON and could not be deserialized, it ends up being a ByteArray message that gets published.
      # the JSON serializer will still serialize the ByteArray as a string, but it will be a string of bytes, not a string of characters.
      # See WaterAllocationConsumerErrorHandlerTest
      # Can't figure out a good way to avoid this without writing a custom serializer.
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    streams:
      properties:
        num.stream.threads: 2
        max.poll.records: 10
        default:
          key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      application-id: nz.govt.eop.consumers.manager

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

server:
  compression:
    enabled: true
    mime-types: application/json

logging:
  level:
    root: INFO
    nz.govt.eop: DEBUG
    org.jooq.Constants: OFF
    org.jooq: INFO
    org.apache.kafka: INFO
    org.apache.kafka.streams.processor.internals.assignment.RackAwareTaskAssignor: OFF # Because it logs an error at startup even though it isn't used.

tangata.whenua.sites:
  sources:
    - name: "Schedule C"
      urls:
        - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/NRPMap_P_operative/MapServer/4/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=location,Values_&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson"
        - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/NRPMap_P_operative/MapServer/5/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=location,Values_&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson"
        - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/NRPMap_P_operative/MapServer/6/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=location,Values_&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson"
        - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/NRPMap_P_operative/MapServer/7/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=location,Values_&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson"
        - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/NRPMap_P_operative/MapServer/8/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=location,Values_&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson"

    - name: "Schedule B"
      urls:
        - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/NRPMap_P_operative/MapServer/2/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=Name%2CMana_Whenua%2CDescription%2CNg%C4%81_Huanga_M%C4%81ori_values%2CNg%C4%81_Mahi_a_ng%C4%81_T%C5%ABpuna%2CTe_Mahi_Kai%2CTe_Mana_o_te_Tangata%2CTe_Manawaroa_o_te_Wai%2CTe_Mana_o_te_Wai%2CW%C4%81hi_Mahara%2CW%C4%81hi_Whakarite%2CTe_H%C4%81_o_te_Ora&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=geojson"

org:
  contact:
    email: "${CONFIG_ORG_CONTACT_EMAIL:org-contact-email-missing}"

linz:
  koord:
    api:
      base-url: "${CONFIG_LINZ_KOORD_BASE_URL:https://data.linz.govt.nz}"
      key: "${CONFIG_LINZ_KOORD_API_KEY:}"
  address:
    boundary:
      timeout: 10000

addressfinder:
  api:
    key: "${CONFIG_ADDRESSFINDER_API_KEY:}"
    secret: "${CONFIG_ADDRESSFINDER_API_SECRET:}"
    base-url: "${CONFIG_ADDRESSFINDER_BASE_URL:https://api.addressfinder.io/api/nz/address}"

freshwater:
  management:
    units:
      sources:
        - name: "arcgis"
          urls:
            - "https://mapping.gw.govt.nz/arcgis/rest/services/GW/Ruamahanga_Whaitua_FMU_Objectives_V1/FeatureServer&f=geojson"

