spring:
  datasource:
    url: jdbc:postgresql://${CONFIG_DATABASE_HOST:localhost}:${CONFIG_DATABASE_PORT:5432}/${CONFIG_DATABASE_NAME:eop_dev}
    username: ${CONFIG_DATABASE_USERNAME:postgres}
    password: ${CONFIG_DATABASE_PASSWORD:password}

server:
  compression:
    enabled: true
    mime-types: application/json