spring:
  flyway:
    locations: classpath:/db/migration # In production don't want to pick up test migrations

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_BROKERS}
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_SASL_USERNAME}" password="${KAFKA_SASL_PASSWORD}";
management:
  endpoints:
    enabled-by-default: false
  web:
    exposure:
      include: "health"
  endpoint:
    health:
      enabled: true

logging:
  level:
    root: WARN
    nz.govt.eop: INFO
    org.springframework.web.servlet.resource.ResourceHttpRequestHandler: ERROR # this logs WARN's for paths that are probably being scanned by bots
    org.apache.kafka: WARN
