spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${CONFIG_DATABASE_HOST:localhost}:${CONFIG_DATABASE_PORT:5432}/${CONFIG_DATABASE_NAME:eop_dev}
    username: ${CONFIG_DATABASE_USERNAME:postgres}
    password: ${CONFIG_DATABASE_PASSWORD:password}

  flyway:
    locations: classpath:/db/migration,classpath:/db/migration-dev

server:
  compression:
    enabled: true
    mime-types: application/json

logging:
  level:
    org.jooq.Constants: OFF