name: Docs Site Build

on:
  push:
    branches:
      - *
      - !main
    paths:
        - .github/workflows/docs-site-deploy.yml
        - docs-site/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs-site
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v2

      - name: Build docs
        run: ./batect build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs-site/public
