name: Manager

permissions:
    id-token: write
    contents: read

on:
  push:
    paths:
      - .github/workflows/manager.yml
      - packages/Manager/**

env:
  WORKING_DIR: ./packages/Manager

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/Manager

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache Batect
        uses: actions/cache@v3.2.4
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles(format('{0}/batect', env.WORKING_DIR)) }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.2.4
        id: cache-packages
        with:
          path: ${{ env.WORKING_DIR }}/.batect/caches
          key: batect-caches-${{ hashFiles(format('{0}/**/*.gradle.kts', env.WORKING_DIR)) }}

      - name: Check app
        run: ./batect check

      - name: Build app
        run: ./batect build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
            aws-region: ap-southeast-2
            role-to-assume: arn:aws:iam::898449181946:role/allow-auto-deploy-from-other-accounts
            role-duration-seconds: 1200
            role-session-name: GitHubActions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: eop-manager
        run: |
             echo "$ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA"
             docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
             docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA