name: Manager

on:
  push:
    paths:
      - .github/workflows/manager.yml
      - packages/Manager/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/Manager
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build app
        run: ./batect build
