name: Plan Limits UI

on:
  push:
    paths:
      - .github/workflows/plan-limits-ui.yml
      - packages/LocalInfrastructure/**
      - packages/PlanLimitsUI/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/PlanLimitsUI
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app
        run: ./batect --config-var git_sha=${GITHUB_SHA} --config-var linz_api_key=${{ secrets.LINZ_API_KEY }} build
