name: Plan Limits UI

on:
  push:
    paths:
      - .github/workflows/plan-limits-ui.yml
      - packages/PlanLimitsUI/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/PlanLimitsUI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build app
        run: ./batect --config-var git_sha=${GITHUB_SHA} --config-var linz_api_key=${{ secrets.LINZ_API_KEY }} build

      - name: Upload Distribution Files
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./packages/PlanLimitsUI/dist/

  deploy-dev:
    name: Deploy Dev
    needs: build
    if: github.ref == 'refs/heads/deploy/dev'
    uses: ./.github/workflows/plan-limits-ui-deploy.yml    
    with:
      environment: plan-limits-dev  
    secrets: inherit

  deploy-stage:
    name: Deploy Stage
    needs: build

    if: github.ref == 'refs/heads/deploy/stage'
    uses: ./.github/workflows/plan-limits-ui-deploy.yml    
    with:
      environment: plan-limits-stage    
    secrets: inherit

  deploy-prod:
    name: Deploy Prod
    needs: build
    if: github.ref == 'refs/heads/deploy/prod'
    uses: ./.github/workflows/plan-limits-ui-deploy.yml    
    with:
      environment: plan-limits-prod    
    secrets: inherit    