name: Plan Limits UI

on:
  push:
    paths:
      - .github/workflows/plan-limits-ui.yml  
      - ./packages/PlanLimitsUI/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/PlanLimitsUI
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docs
        run: ./batect build
