name: Plan Limits UI Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string 

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  deploy:
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/PlanLimitsUI
    steps:
      - name: Download Distribution Files
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./packages/PlanLimitsUI/dist/

      - name: Configure Environment Access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/allow-auto-deploy-from-other-accounts
          role-duration-seconds: 1200
          role-session-name: GithubActions-Deploy

      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }} --region ap-southeast-2 --cache-control max-age=31536000,public --exclude "index.html"
          aws s3 cp dist/index.html s3://${{ secrets.AWS_S3_BUCKET }} --region ap-southeast-2 --metadata-directive REPLACE --cache-control no-cache,public --content-type text/html
